// * DEFAULT OBJECTS * \\

export const INITIAL_STATE = {
  loading: false,
  results: [],
  count: 0,
  limit: 28,
  offset: 0,
  total: 0
}

// * ACTION TYPES * \\
export const CHARACTERS_LIST_REQUEST = 'CHARACTERS_LIST_REQUEST'
export const CHARACTERS_LIST_SUCCESS = 'CHARACTERS_LIST_SUCCESS'
export const CHARACTERS_LIST_NEXT_REQUEST = 'CHARACTERS_LIST_NEXT_REQUEST'
export const CHARACTERS_LIST_NEXT_SUCCESS = 'CHARACTERS_NEXT_LIST_SUCCESS'
export const CHARACTERS_DETAIL_REQUEST = 'CHARACTERS_DETAIL_REQUEST'
export const CHARACTERS_DETAIL_SUCCESS = 'CHARACTERS_DETAIL_SUCCESS'
export const CHARACTERS_SAVE_REQUEST = 'CHARACTERS_SAVE_REQUEST'
export const CHARACTERS_SAVE_SUCCESS = 'CHARACTERS_SAVE_SUCCESS'
